deployments:
## Tensorizer with lazy load
- load_format: "tensorizer"
  plaid_mode: ""
  lazy_load: "--lazy-load"
## Tensorizer with no lazy load
- load_format: "tensorizer"
  plaid_mode: ""
  lazy_load: ""
## Tensorizer with lazy load and vllm-formatted model and plaid mode
- load_format: "tensorizer"
  plaid_mode: "--plaid-mode"
  lazy_load: "--lazy-load"
## Tensorizer with no lazy load and vllm-formatted model and plaid mode
- load_format: "tensorizer"
  plaid_mode: "--plaid-mode"
  lazy_load: ""
## Safetensors
- load_format: "safetensors"
  plaid_mode: ""
  lazy_load: ""
## Npcache
- load_format: "npcache"
  plaid_mode: ""
  lazy_load: ""