apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}-tests
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ${APP_NAME}-tests
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ${APP_NAME}-tests
    spec:
      containers:
        - name: setup-container
          image: "public.ecr.aws/q9t5s3a7/vllm-ci-test-repo:aff16e73f171a000fb159286d6c8ac4f799bcf34"
          env:
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-secret
                  key: token
          workingDir: /vllm-workspace
          command:
            - "/bin/sh"
            - "-c"
            - |
              sleep 3600
              # pytest -v -s tests/entrypoints/openai/test_tensorizer_entrypoint.py

          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: ssh-key
              mountPath: "/keys"
              readOnly: true
          resources:
            requests:
              cpu: "32"
              memory: 128Gi
              nvidia.com/gpu: "4"
            limits:
              cpu: "32"
              memory: 128Gi
              nvidia.com/gpu: "4"
      imagePullSecrets:
        - name: ghcr-image-secret
        - name: hf-secret
      volumes:
        - name: ssh-key
          secret:
            secretName: ssh-mac-pubkey
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values:
                  - "ORD1"
              - key: gpu.nvidia.com/class
                operator: In
                values:
                  - "A100_PCIE_80GB"